---
title: "My Homepage"
---
Resourceful and highly motivated junior data analyst, skilled in data analysis and machine learning methods. Seeking to my skills to help organizations in decision-making and boosting business performance. Proven to be adept in problem solving, research and encouraging team work. Moreover I have shown ability to meet deadlines without compromising the accuracy and quality of work.

On this website, I post some of the projects I've done and the services I offer.

## Key Skills

<style>
  .col2 {
    columns: 2 100px;
    -webtik-columns: 2 100px
    -moz-columns: 2 100px;
}
</style>

<div class="col2">

* Coding - R, Latex
* Advanced Microsoft Excel
* Data analysis
* Data visualization - Tableau, Ggplot, Shiny R
* Data modelling - Regression, Random Forest, Time series
* Forecasting - Time series
* Hypothesis testing
* Inferential statistics
* Report writing on data analysis findings
* Research


</div>
 
## Soft Skills

* Problem solving
* Analytical 
* Detail oriented
* Communication and interpersonal skills
* Team player
* Self motivated

## Services

* Data analysis with R and Microsoft Excel
* Statistics and Math assignments
* Math tutoring 
* Essay and report writing
* Data entry tasks
* Undergraduate projects
 
## Experience

<i class="fa fa-briefcase"></i><font size="3"> **Data Analyst Intern**, *Kenya Revenue Authority*

Jan 2022-Dec 2022

<i class="fa fa-briefcase"></i><font size="3"> **Data Analyst**, *Freelance* 

Jan 2020- Present

<i class="fa fa-briefcase"></i><font size="3"> **In- home Tutor**, *Freelance* 

Aug 2021-Dec 2021

## Education

<i class="fa fa-graduation-cap"></i><font size="3"> **Bachelor of Science in Statistics**, *University of Nairobi*

Sep 2021

## Certificates

<i class="fa fa-award"></i><font size="3"> **R Statistical Data Analysis Training**, *University of Nairobi* </font>

2022





